# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(33, 33, 33)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.transportTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.transportTableWidget.setGeometry(QtCore.QRect(640, 439, 640, 361))
        self.transportTableWidget.setStyleSheet("")
        self.transportTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.transportTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.transportTableWidget.setAutoScroll(False)
        self.transportTableWidget.setObjectName("transportTableWidget")
        self.transportTableWidget.setColumnCount(3)
        self.transportTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.transportTableWidget.setItem(0, 2, item)
        self.transportTableWidget.horizontalHeader().setDefaultSectionSize(208)
        self.transportTableWidget.verticalHeader().setDefaultSectionSize(60)
        self.datetimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.datetimeLabel.setGeometry(QtCore.QRect(0, 0, 1280, 161))
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(90)
        self.datetimeLabel.setFont(font)
        self.datetimeLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.datetimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datetimeLabel.setObjectName("datetimeLabel")
        self.toDoTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.toDoTableWidget.setGeometry(QtCore.QRect(0, 169, 640, 631))
        self.toDoTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.toDoTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.toDoTableWidget.setAutoScroll(False)
        self.toDoTableWidget.setObjectName("toDoTableWidget")
        self.toDoTableWidget.setColumnCount(2)
        self.toDoTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.toDoTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.toDoTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.toDoTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.toDoTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.toDoTableWidget.setItem(0, 1, item)
        self.toDoTableWidget.horizontalHeader().setDefaultSectionSize(312)
        self.toDoTableWidget.verticalHeader().setDefaultSectionSize(60)
        self.heartbeatTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.heartbeatTableWidget.setGeometry(QtCore.QRect(640, 169, 640, 271))
        self.heartbeatTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heartbeatTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.heartbeatTableWidget.setAutoScroll(False)
        self.heartbeatTableWidget.setObjectName("heartbeatTableWidget")
        self.heartbeatTableWidget.setColumnCount(2)
        self.heartbeatTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.heartbeatTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.heartbeatTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.heartbeatTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.heartbeatTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Noto Serif CJK TC Black")
        font.setPointSize(24)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.heartbeatTableWidget.setItem(0, 1, item)
        self.heartbeatTableWidget.horizontalHeader().setDefaultSectionSize(312)
        self.heartbeatTableWidget.verticalHeader().setDefaultSectionSize(60)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.transportTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.transportTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "路線"))
        item = self.transportTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "車牌號碼"))
        item = self.transportTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "到站剩餘時間"))
        __sortingEnabled = self.transportTableWidget.isSortingEnabled()
        self.transportTableWidget.setSortingEnabled(False)
        item = self.transportTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1815"))
        item = self.transportTableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "進站中"))
        self.transportTableWidget.setSortingEnabled(__sortingEnabled)
        self.datetimeLabel.setText(_translate("MainWindow", "2021/08/12 23:59:59"))
        item = self.toDoTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.toDoTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "描述"))
        item = self.toDoTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "到期日"))
        __sortingEnabled = self.toDoTableWidget.isSortingEnabled()
        self.toDoTableWidget.setSortingEnabled(False)
        item = self.toDoTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", " 戴口罩"))
        item = self.toDoTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "08/31"))
        self.toDoTableWidget.setSortingEnabled(__sortingEnabled)
        item = self.heartbeatTableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.heartbeatTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名稱"))
        item = self.heartbeatTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "狀態"))
        __sortingEnabled = self.heartbeatTableWidget.isSortingEnabled()
        self.heartbeatTableWidget.setSortingEnabled(False)
        item = self.heartbeatTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Raspi-Palor"))
        item = self.heartbeatTableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "回應正常"))
        self.heartbeatTableWidget.setSortingEnabled(__sortingEnabled)
